name: Java CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and package
      run: |
        ./mvnw clean package spring-boot:repackage
        ls target/jwt-auth-service-1.0.0.jar

    - name: Fetch JAR file
      run: |
        mkdir -p ${{ github.workspace }}/artifacts
        cp target/jwt-auth-service-1.0.0.jar ${{ github.workspace }}/artifacts

  transfer:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Transfer JAR file
      run: |
        mkdir -p target
        cp ${{ github.workspace }}/artifacts/jwt-auth-service-1.0.0.jar target/
